=== eviko/Exercise-XML/events.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="events">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="event" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:choice maxOccurs="unbounded" minOccurs="0">
              <xs:element name="category">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="genre" use="optional"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="title">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="lang" use="optional"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="artists">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="artist" maxOccurs="unbounded" minOccurs="0"/>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="kind" use="optional"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="venue">
                <xs:complexType>
                  <xs:choice maxOccurs="unbounded" minOccurs="0">
                    <xs:element type="xs:string" name="event_place"/>
                    <xs:element type="xs:dateTime" name="starting"/>
                    <xs:element type="xs:string" name="address"/>
                    <xs:element name="cost">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:decimal">
                            <xs:attribute type="xs:string" name="currency" use="optional"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element type="xs:anyURI" name="url"/>                    
                  </xs:choice>
                </xs:complexType>
              </xs:element>
              <xs:element type="xs:string" name="event_details"/>
            </xs:choice>
            <xs:attribute type="xs:string" name="event_id" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== eviko/Exercise-XML/events.xml
<?xml version="1.0" encoding="UTF-8"?>
<events xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="events.xsd">
 <event event_id="﻿E0-001-086220859-4">
    <category  genre="rap">Concerts</category>
    <title lang="en">Hollywood Undead</title>
    <artists kind="band">
      <artist>Jore</artist>
      <artist>Matthew</artist>
      <artist>Dylan</artist>
      <artist>George</artist>
      <artist>Jordon</artist>
      <artist>Daniel</artist>
  </artists>
  <venue>
   <event_place>Huxley's Neue Welt</event_place>
   <starting>2016-03-30T20:00:00</starting>
   <address>Hasenheide 108-114 Berlin, Berlin 10967 ,Germany</address>
   <cost currency="euro">33.95</cost>
   <url>http://berlin.eventful.com/events/hollywood-undead-/E0-001-088495749-3</url>
  </venue>
   <event_details>Official Website </event_details>
   <event_details> Event details at huxleysneuewelt.com! </event_details>
   <event_details> Event details at hekticket.de!</event_details>
 </event>
 <event event_id="E0-001-086220859-5">
  <category genre="Alternative Rock">Concerts</category>
  <artists kind="band">
    <artist>Black Franci</artist>
    <artist>Joey Santiago</artist>
    <artist>Paz Lenchantin</artist>
    <artist>David Lovering</artist>
</artists>
  <title lang="en">Pixies</title>
  <venue>
   <event_place>Zitadelle Spandau</event_place>
   <starting>2016-07-18T20:00:00</starting>
   <address>Am Juliusturm 64, Berlin 13599  ,Germany</address>
   <cost currency="euro">70.45</cost>
   <cost currency="euro">80.40</cost>
   <cost currency="euro">96.48</cost>
   <url>http://berlin.eventful.com/events/pixies-/E0-001-090893869-5</url>
  </venue>
   <event_details>Buy tickets at viagogo.com! </event_details>
   <event_details> Event details at hekticket.de!</event_details>
 </event>
 <event event_id="E0-001-086220859-6">
  <category genre="Alternative Rock">Concerts</category>
  <title lang="en">The Cure</title>
  <artists kind="band">
    <artist>Robert Smith</artist>
    <artist>Lol Tolhurst</artist>
    <artist>Porl Thompson</artist>
  </artists>
  <venue>
   <event_place>Mercedes Benz Arena </event_place>
   <starting>2016-10-18T19:30:00</starting>
   <address>Mercedes-Platz 1 , Berlin 10243 ,Germany</address>
   <cost currency="euro">79.50</cost>
   <cost currency="euro">99.00</cost>
   <cost currency="euro">112.37</cost>
   <url>http://berlin.eventful.com/events/cure-berlin-/E0-001-089188325-7</url>
  </venue>
   <event_details> Event details at hekticket.de!</event_details>
 </event>
 <event event_id="E0-001-086220859-7">
  <category  genre="Alternative Rock">Concerts</category>
    <artists kind="band">
   <artist >Brian Molko</artist>
    <artist >Stefan Olsdal</artist>
  </artists>
  <title lang="en">Placebo </title>
  <venue>
   <event_place>Mercedes Benz Arena </event_place>
   <starting>2016-11-07T20:00:00</starting>
   <address>Mercedes-Platz 1 , Berlin 10243 ,Germany</address>
   <cost currency="euro">59.70</cost>
   <cost currency="euro">79.85</cost>
   <cost currency="euro">89.67</cost>
   <cost currency="euro">99</cost>
   <url>http://berlin.eventful.com/events/placebo-/E0-001-091927233-7</url>
  </venue>
 </event>
 <event event_id="E0-001-086220859-8">
  <category genre="Pop">Concerts</category>
  <title lang="en">Rihanna</title>
  <artists kind="singer">
    <artist>Rihanna</artist>
</artists>
   <venue>
   <event_place>Olympiastadion</event_place>
   <starting>2016-08-02T20:00:00</starting>
   <address>Olympischer Platz 3, 14053 Berlin ,Germany</address>
   <cost currency="euro">120.52</cost>
   <url>http://berlin.eventful.com/events/rihanna-berlin-/E0-001-089188317-8</url>
  </venue>
   <event_details> Event details at hekticket.de!</event_details>
   </event>
 <event event_id="E0-001-086220859-9">
  <category genre="Pop">Concerts</category>
  <title lang="en">David Blair</title>
  <artists kind="singer">
    <artist >David Blair</artist>
 </artists>
  <venue>
   <event_place>ART STALKER</event_place>
   <starting>2016-08-07T20:30:00</starting>
   <cost currency="euro">8.00</cost>
   <cost currency="euro">5.00</cost>
   <address>KAISER-FRIEDRICH STR. 67 Berlin ,Germany</address>
   <url>http://berlin.eventful.com/events/david-blair-concert-/E0-001-086220859-9?utm_source=apis&amp;utm_medium=apim&amp;utm_campaign=apic</url>
  </venue>
   <event_details>Event details at eventbrite.com! </event_details>
   <event_details> Artist details at reverbnation.com!</event_details>
 </event>
 <event event_id="E0-001-087755126-4">
  <category genre="Folk">Concerts</category>
  <title lang="en">THE SAY HIGHS </title>
  <artists kind="band">
    <artist>Dave McGinty</artist>
    <artist>Guido Kreutzm?ller</artist>
 </artists>
  <venue>
   <event_place>ART STALKER</event_place>
   <starting>2016-10-27T20:30:00</starting>
   <url>http://berlin.eventful.com/events/say-highs-folk-concert-/E0-001-087755126-4?utm_source=apis&amp;utm_medium=apim&amp;utm_campaign=apic</url>
   <address>KAISER-FRIEDRICH STR. 67 Berlin ,Germany</address>
   <cost currency="euro">6.00</cost>
   <cost currency="euro">8.50</cost>
  </venue>
   <event_details>Event details at eventbrite.com! </event_details>
   <event_details> Artist details at reverbnation.com!</event_details>
 </event>
 <event event_id="E0-001-081323578-0">
  <category genre="soul">Concerts</category>
  <title lang="en">Mara Simpson</title>
  <artists kind="band">
    <artist>Chris Boot</artist>
    <artist>Ben Daniels</artist>
    <artist >Rene Corbett</artist>
    <artist >Alex Bayer</artist>
    <artist >Susy Peddie</artist>
  </artists>
  <venue>
   <event_place>Konzerthaus Berlin</event_place>
   <starting>2016-04-10T20:00:00</starting>
   <address>Gendarmenmarkt 10117 Berlin ,Germany</address>
   <cost currency="euro">10.0</cost>
   <url>http://berlin.eventful.com/events/house-concert-mara-simpson-/E0-001-081323578-0?utm_source=apis&amp;utm_medium=apim&amp;utm_campaign=apic</url>
  </venue>
   <event_details>musicglue.com!</event_details>
 </event>
 <event event_id="E0-001-089234427-8">
  <category genre="hip hop">Concerts</category>
  <title lang="en">M.O.P.</title>
  <artists kind="duo">
    <artist >Lil' Fame</artist>
    <artist >Billy Danze</artist>
  </artists>
  <venue>
   <event_place>Lido</event_place>
   <starting>2015-12-18T20:00:00</starting>
   <cost currency="euro">15</cost>
   <address> Cuvrystr 7, Berlin 10997 ,Germany</address>
   <url>http://berlin.eventful.com/events/mop-live-concert-/E0-001-089234427-8?utm_source=apis&amp;utm_medium=apim&amp;utm_campaign=apic</url>
  </venue>
   <event_details> Event details at lido-berlin.de! </event_details>
   <event_details> Event details at adticket.de!</event_details>
 </event>
 <event event_id="GR-020-15236">
  <category genre="Dance theater">Dance</category>
  <title lang="en">TAO Dance Theater</title>
  <artists kind="group">
    <artist >Fu Liwei</artist>
    <artist >Mao Xue</artist>
    <artist >Li Shunjie</artist>
    <artist >Yu Jinying</artist>
    <artist >Huang li</artist>
    <artist >Hu Jing</artist>
  </artists>
  <venue>
   <event_place>ONASSIS Cultural Center </event_place>
   <starting>2016-04-04T20:30:00</starting>
   <url>http://www.sgt.gr/eng/SPG1398/?</url>
   <address>107-109 SyngrouAvenue,11745 Athens,Greece</address>
   <cost currency="euro"> 18</cost>
   <cost currency="euro">15</cost>
   <cost currency="euro">5</cost>
  </venue>
 </event>
 <event event_id="GR-020-15237">
  <category genre="Dance theater">Dance</category>
  <title lang="gr">Δεσποινίς Τζούλια</title>
  <artists kind="group">
   <artist >Εύα Παρασκευοπούλου</artist>
    <artist >Στ. Λίτινας</artist>
    <artist >Αλ. Αναστασιάδη</artist>
  </artists>
  <venue>
   <event_place>Anesis</event_place>
   <starting>2016-04-04T20:30:00</starting>
   <address>14 Kifisias Avenue,11526 Athens,Greece</address>
   <cost currency="euro">14.00</cost>
   <cost currency="euro">10</cost>
   <url>http://www.athinorama.gr/theatre/performance/despoinis_tzoulia-10030274.html</url>
  </venue>
 </event>
 <event event_id="GR-020-15238">
 <category genre="Dance theater">Dance</category>
  <title lang="en">Compagnie Maguy Marin</title>
<artists kind="group">
  <artist>Ulises Alvarez</artist>
  <artist>Kais Chouibi</artist>
  <artist>Laura Frigato</artist>
  <artist>Daphn? Koutsafti</artist>
  <artist>Mayalen Otondo</artist>
  <artist>Cathy Polo</artist>
  <artist>Ennio Sammarco</artist>
</artists>
  <venue>
   <event_place>Peiraios 260, Building D</event_place>
   <starting>2015-06-02T21:00:00</starting>
   <address>Peiraios 260,18233 Athens,Greece</address>
   <cost currency="euro">25</cost>
   <cost currency="euro">20</cost>
   <cost currency="euro">15</cost>
   <cost currency="euro">10</cost>
   <cost currency="euro">5</cost>
   <url>http://greekfestival.gr/en/events/view/compagnie-maguy-marin-2015</url>
  </venue>
 </event>
 <event event_id="GR-020-15239">
 <category genre="Dance theater">Dance</category>
  <title lang="en">Sylvie Guillem</title>
  <artists kind="solo">
    <artist >Sylvie Guillem</artist>
</artists>
  <venue>
   <event_place>Odeon of Herodes Atticus</event_place>
    <starting>2015-06-03T20:00:00 </starting>
   <address>  Dionysiou Areopagitou Street,15123,Athens,Greece</address>
   <cost currency="euro">50</cost>
   <cost currency="euro">40</cost>
   <cost currency="euro">35</cost>
   <cost currency="euro">15</cost>
   <cost currency="euro">10</cost>
   <url>http://greekfestival.gr/en/events/view/sylvie-guillem-2015</url>
  </venue>
 </event>
<event event_id="GR-020-15280">
 <category genre="Dance theater">Dance</category>
  <title lang="en">Sylvie Guillem</title>
  <artists kind="solo">
    <artist >Sylvie Guillem</artist>
</artists>
  <venue>
   <event_place>Peiraios 260, Building D</event_place>
  <starting>2016-08-13T21:00:00 </starting>   
   <address>Peiraios 260,18233 Athens,Greece</address>
